### ISSUE TITLE
thrust::system::detail::bad_alloc error

### ISSUE THREAD

**Issue by xiaoyaoing** [facebookresearch/HairMSNN#2]
When the class renderWindow_hairmsnn is executing the render function, an error occurs in the method train. Specifically, an unknown memory error occurs when calling "(float*)owlBufferGetPointer(this->nnTrainInput, 0)" on line 680.
However, the strange thing is that the train function called when the window is initialized does not error.
Since I don't know much about owl, I don't know how to solve this problem, if I can get help, I will be very grateful.
Environment: Visual Studio 2022 Windows10 CUDA12.1, the specific error pictures are as follows
![image](https://github.com/facebookresearch/HairMSNN/assets/56785727/f5a0d682-4765-4e56-ad55-09a45b030beb)

**Comment by AakashKT** [comment]
Hi,

Could you please send me your scene configuration? Also, does your system have more than one GPU?
This is a strange error indeed!

Thanks,
Aakash

**Comment by xiaoyaoing** [comment]
Oh, I've resolved this issue. I was using OptiX 8.0 previously, but after switching to version 7.4, everything is working fine now. Thank you for your response, and I wish you all the best！

**Comment by AakashKT** [comment]
Awesome! Thanks, let me know if you encounter other issues.
