### ISSUE TITLE
Unable to reproduce the results from the paper

### ISSUE THREAD

**Issue by xiaoyaoing** [facebookresearch/HairMSNN#3]
Hello, when I run the project and set beta to 1, and change the color output to only include the network part, the output seems to differ significantly from the path tracing results. Can you please help me understand why? The scene setup and results are as shown in the following image. I would greatly appreciate any insights.
![image](https://github.com/facebookresearch/HairMSNN/assets/56785727/c3af5858-48b6-4a7e-8786-c38fff7e74bf)

**Comment by AakashKT** [comment]
Hello,

Apologiescfor the late response.

Please refer to Fig. 3 and the "discussion" in Sect. 4 of the paper. The network output directly is expected to be this way, especially for lower values of beta like you've shown.

The network output for beta and beyond, along with path tracing upto beta is to be combined for final rendering.

Does this make sense?

**Comment by xiaoyaoing** [comment]
Thank you for your response, I have understood your meaning, thank you!
